"""add Expired field

Revision ID: 3f0ffefad32d
Revises: d0f082805efd
Create Date: 2022-10-26 19:34:42.490278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0ffefad32d'
down_revision = 'd0f082805efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_expired', sa.Boolean(), server_default='False', nullable=True))
    op.alter_column('tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tokens', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('tokens_token_key', 'tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tokens_token_key', 'tokens', ['token'])
    op.alter_column('tokens', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tokens', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tokens', 'is_expired')
    # ### end Alembic commands ###
